name: docker
category: container
version: "24.0.9"
labels:
  github.repo: "moby"
  github.owner: "moby"
uri:
  - https://dockerproject.org
license: "Apache-2.0"

description: "Docker provides a simple and powerful developer experience, workflows and collaboration for creating applications"
